<?php

use Illuminate\Database\Seeder;
use App\Models\Services\Declarations\SevenTowCero\CountryCode;

class CountryCodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        DB::table('sv_iso_country_cod')->truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        CountryCode::create(['cod'=>'AF','value'=>'AFGANISTÁN']);
        CountryCode::create(['cod'=>'AL','value'=>'ALBANIA']);
        CountryCode::create(['cod'=>'DE','value'=>'ALEMANIA']);
        CountryCode::create(['cod'=>'AD','value'=>'ANDORRA']);
        CountryCode::create(['cod'=>'AO','value'=>'ANGOLA']);
        CountryCode::create(['cod'=>'AI','value'=>'ANGUILA']);
        CountryCode::create(['cod'=>'AQ','value'=>'ANTÁRTIDA']);
        CountryCode::create(['cod'=>'AG','value'=>'ANTIGUA Y BARBUDA']);
        CountryCode::create(['cod'=>'SA','value'=>'ARABIA SAUDÍ']);
        CountryCode::create(['cod'=>'DZ','value'=>'ARGELIA']);
        CountryCode::create(['cod'=>'AR','value'=>'ARGENTINA']);
        CountryCode::create(['cod'=>'AM','value'=>'ARMENIA']);
        CountryCode::create(['cod'=>'AW','value'=>'ARUBA']);
        CountryCode::create(['cod'=>'AU','value'=>'AUSTRALIA']);
        CountryCode::create(['cod'=>'AT','value'=>'AUSTRIA']);
        CountryCode::create(['cod'=>'AZ','value'=>'AZERBAIYÁN']);
        CountryCode::create(['cod'=>'BS','value'=>'BAHAMAS']);
        CountryCode::create(['cod'=>'BH','value'=>'BAHRÉIN']);
        CountryCode::create(['cod'=>'BD','value'=>'BANGLADESH']);
        CountryCode::create(['cod'=>'BB','value'=>'BARBADOS']);
        CountryCode::create(['cod'=>'BE','value'=>'BÉLGICA']);
        CountryCode::create(['cod'=>'BZ','value'=>'BELICE']);
        CountryCode::create(['cod'=>'BJ','value'=>'BENÍN']);
        CountryCode::create(['cod'=>'BM','value'=>'BERMUDAS']);
        CountryCode::create(['cod'=>'BY','value'=>'BIELORUSIA (BELARÚS)']);
        CountryCode::create(['cod'=>'BO','value'=>'BOLIVIA']);
        CountryCode::create(['cod'=>'BA','value'=>'BOSNIA-HERZEGOVINA']);
        CountryCode::create(['cod'=>'BW','value'=>'BOTSUANA']);
        CountryCode::create(['cod'=>'BV','value'=>'BOUVET, ISLA']);
        CountryCode::create(['cod'=>'BR','value'=>'BRASIL']);
        CountryCode::create(['cod'=>'BN','value'=>'BRUNÉI (BRUNÉI DARUSSALAM)']);
        CountryCode::create(['cod'=>'BG','value'=>'BULGARIA']);
        CountryCode::create(['cod'=>'BF','value'=>'BURKINA FASO (Alto Volta)']);
        CountryCode::create(['cod'=>'BI','value'=>'BURUNDI']);
        CountryCode::create(['cod'=>'BT','value'=>'BUTÁN']);
        CountryCode::create(['cod'=>'CV','value'=>'CABO VERDE, REPÚBLICA DE']);
        CountryCode::create(['cod'=>'KY','value'=>'CAIMÁN, ISLAS']);
        CountryCode::create(['cod'=>'KH','value'=>'CAMBOYA']);
        CountryCode::create(['cod'=>'CM','value'=>'CAMERÚN']);
        CountryCode::create(['cod'=>'CA','value'=>'CANADÁ']);
        CountryCode::create(['cod'=>'CF','value'=>'CENTROAFRICANA, REPÚBLICA']);
        CountryCode::create(['cod'=>'CC','value'=>'COCOS, ISLA DE (KEELING)']);
        CountryCode::create(['cod'=>'CO','value'=>'COLOMBIA']);
        CountryCode::create(['cod'=>'KM','value'=>'COMORAS (Gran Comora, Anjouan y Mohéli)']);
        CountryCode::create(['cod'=>'CG','value'=>'CONGO']);
        CountryCode::create(['cod'=>'CD','value'=>'CONGO, REPÚBLICA DEMOCRÁTICA DEL (Zaire)']);
        CountryCode::create(['cod'=>'CK','value'=>'COOK, ISLAS']);
        CountryCode::create(['cod'=>'KP','value'=>'CPREA DEL NORTE (República Popular Democrática de Core)']);
        CountryCode::create(['cod'=>'KR','value'=>'COREA DEL SUR (República de Corea)']);
        CountryCode::create(['cod'=>'CI','value'=>'COSTA DE MARFIL']);
        CountryCode::create(['cod'=>'CR','value'=>'COSTA RICA']);
        CountryCode::create(['cod'=>'HR','value'=>'CROACIA']);
        CountryCode::create(['cod'=>'CU','value'=>'CUBA']);
        CountryCode::create(['cod'=>'TD','value'=>'CHAD']);
        CountryCode::create(['cod'=>'CZ','value'=>'CHECA, REPÚBLICA']);
        CountryCode::create(['cod'=>'CL','value'=>'CHILE']);
        CountryCode::create(['cod'=>'CN','value'=>'CHINA']);
        CountryCode::create(['cod'=>'CY','value'=>'CHIPRE']);
        CountryCode::create(['cod'=>'CW','value'=>'CURAÇAO (Antes en Antillas Neerlandesas)']);
        CountryCode::create(['cod'=>'DK','value'=>'DINAMARCA']);
        CountryCode::create(['cod'=>'DM','value'=>'DOMINICA']);
        CountryCode::create(['cod'=>'DO','value'=>'DOMINICANA, REPÚBLICA']);
        CountryCode::create(['cod'=>'EC','value'=>'ECUADOR (Incluídas las Islas Galápagos)']);
        CountryCode::create(['cod'=>'EG','value'=>'EGIPTO']);
        CountryCode::create(['cod'=>'AE','value'=>'EMIRATOS ÁRABES UNIDOS (Abu Dabi, Dubai, Sharya, Ayman, Umm al-Qaiwain, Ras al-Jaima y Fuyaira)']);
        CountryCode::create(['cod'=>'ER','value'=>'ERITREA']);
        CountryCode::create(['cod'=>'SK','value'=>'ESLOVAQUIA']);
        CountryCode::create(['cod'=>'SI','value'=>'ESLOVENIA']);
        CountryCode::create(['cod'=>'ES','value'=>'ESPAÑA']);
        CountryCode::create(['cod'=>'US','value'=>'ESTADOS UNIDOS DE AMÉRICA']);
        CountryCode::create(['cod'=>'EE','value'=>'ESTONIA']);
        CountryCode::create(['cod'=>'ET','value'=>'ETIOPÍA']);
        CountryCode::create(['cod'=>'FO','value'=>'FEROE, ISLAS']);
        CountryCode::create(['cod'=>'PH','value'=>'FILIPINAS']);
        CountryCode::create(['cod'=>'FI','value'=>'FINLANDIA (Incluidas las islas Aland)']);
        CountryCode::create(['cod'=>'FJ','value'=>'FIYI']);
        CountryCode::create(['cod'=>'FR','value'=>'FRANCIA (Incluidos los departamentos franceses de ultramar: Reunión, Guadalupe, Martinica y Guayana Francesa)']);
        CountryCode::create(['cod'=>'GA','value'=>'GABÓN']);
        CountryCode::create(['cod'=>'GM','value'=>'GAMBIA']);
        CountryCode::create(['cod'=>'GE','value'=>'GEORGIA']);
        CountryCode::create(['cod'=>'GS','value'=>'GEORGIA DEL SUR Y LAS ISLAS SENDWICH DEL SUR']);
        CountryCode::create(['cod'=>'GH','value'=>'GHANA']);
        CountryCode::create(['cod'=>'GI','value'=>'GIBRALTAR']);
        CountryCode::create(['cod'=>'GD','value'=>'GRANADA (Incluídas las Islas Granadinas del Sur)']);
        CountryCode::create(['cod'=>'GR','value'=>'GRECIA']);
        CountryCode::create(['cod'=>'GL','value'=>'GROENLANDIA']);
        CountryCode::create(['cod'=>'GU','value'=>'GUAM']);
        CountryCode::create(['cod'=>'GT','value'=>'GUATEMALA']);
        CountryCode::create(['cod'=>'GG','value'=>'GUERNESEY (isla anglonormanda del Canal)']);
        CountryCode::create(['cod'=>'GN','value'=>'GUINEA']);
        CountryCode::create(['cod'=>'GQ','value'=>'GUINEA ECUATORIAL']);
        CountryCode::create(['cod'=>'GW','value'=>'GUINEA-BISSAU']);
        CountryCode::create(['cod'=>'GY','value'=>'GUYANA']);
        CountryCode::create(['cod'=>'HT','value'=>'HAITÍ']);
        CountryCode::create(['cod'=>'HM','value'=>'HEARD Y MCDONALD, ISLAS']);
        CountryCode::create(['cod'=>'HN','value'=>'HONDURAS (incluídas islas de Cisne)']);
        CountryCode::create(['cod'=>'HK','value'=>'HONG-KONG']);
        CountryCode::create(['cod'=>'HU','value'=>'HUNGRÍA']);
        CountryCode::create(['cod'=>'IN','value'=>'INDIA']);
        CountryCode::create(['cod'=>'ID','value'=>'INDONESIA']);
        CountryCode::create(['cod'=>'IR','value'=>'IRÁN']);
        CountryCode::create(['cod'=>'IQ','value'=>'IRAQ']);
        CountryCode::create(['cod'=>'IE','value'=>'IRLANDA']);
        CountryCode::create(['cod'=>'IM','value'=>'ISLA DE MAN']);
        CountryCode::create(['cod'=>'IS','value'=>'ISLANDIA']);
        CountryCode::create(['cod'=>'IL','value'=>'ISRAEL']);
        CountryCode::create(['cod'=>'IT','value'=>'ITALIA (Incluido Livigno)']);
        CountryCode::create(['cod'=>'JM','value'=>'JAMAICA']);
        CountryCode::create(['cod'=>'JP','value'=>'JAPÓN']);
        CountryCode::create(['cod'=>'JE','value'=>'JERSEY (Isla anglonormanda del Canal)']);
        CountryCode::create(['cod'=>'JO','value'=>'JORDANIA']);
        CountryCode::create(['cod'=>'KZ','value'=>'KAZAJSTÁN']);
        CountryCode::create(['cod'=>'KE','value'=>'KENIA']);
        CountryCode::create(['cod'=>'KG','value'=>'KIRGUISTÁN']);
        CountryCode::create(['cod'=>'KI','value'=>'KIRIBATI']);
        CountryCode::create(['cod'=>'KW','value'=>'KUWAIT']);
        CountryCode::create(['cod'=>'LA','value'=>'LAOS (LAO)']);
        CountryCode::create(['cod'=>'LS','value'=>'LESOTHO']);
        CountryCode::create(['cod'=>'LV','value'=>'LETONIA']);
        CountryCode::create(['cod'=>'LB','value'=>'LÍBANO']);
        CountryCode::create(['cod'=>'LR','value'=>'LIBERIA']);
        CountryCode::create(['cod'=>'LY','value'=>'LIBIA']);
        CountryCode::create(['cod'=>'LI','value'=>'LIECHTENSTEIN']);
        CountryCode::create(['cod'=>'LT','value'=>'LITUANIA']);
        CountryCode::create(['cod'=>'LU','value'=>'LUXEMBURGO']);
        CountryCode::create(['cod'=>'XG','value'=>'LUXEMBURGO (por lo que respecta a las rentas percibidas por las Sociedades a que se refi ere el párrafo 1 del protocolo anexo al Convenio de doble imposición (3 junio 1986)']);
        CountryCode::create(['cod'=>'MO','value'=>'MACAO']);
        CountryCode::create(['cod'=>'MK','value'=>'MACEDONIA (Antigua República Yugoslavia)']);
        CountryCode::create(['cod'=>'MG','value'=>'MADAGASCAR']);
        CountryCode::create(['cod'=>'MY','value'=>'MALASIA (Malasia Peninsular y Malasia Oriental: Sarawak, Sabah y Labuán)']);
        CountryCode::create(['cod'=>'MW','value'=>'MALAWI']);
        CountryCode::create(['cod'=>'MV','value'=>'MALDIVAS']);
        CountryCode::create(['cod'=>'ML','value'=>'MALI']);
        CountryCode::create(['cod'=>'MT','value'=>'MALTA (Incluidos Gozo y Comino)']);
        CountryCode::create(['cod'=>'FK','value'=>'MALVINAS, ISLAS (FALKLANDS)']);
        CountryCode::create(['cod'=>'MP','value'=>'MARIANAS DEL NORTE, ISLAS']);
        CountryCode::create(['cod'=>'MA','value'=>'MARRUECOS']);
        CountryCode::create(['cod'=>'MH','value'=>'MARSHALL, ISLAS']);
        CountryCode::create(['cod'=>'MU','value'=>'MAURICIO (Isla Mauricio, Isla Rodrígues, Islas Agalega y Cargados, Carajos Shoals (Islas San Brandón))']);
        CountryCode::create(['cod'=>'MR','value'=>'MAURITANIA']);
        CountryCode::create(['cod'=>'YT','value'=>'MAYOTTE (Gran Tierra y Pamandzi)']);
        CountryCode::create(['cod'=>'UM','value'=>'MENORES ALEJADAS DE LOS EE.UU, ISLAS (Baker, Howland, Jarvis, Johston, Kingman Reef, Midway, Navassa, Palmira y Wake)']);
        CountryCode::create(['cod'=>'MX','value'=>'MÉXICO']);
        CountryCode::create(['cod'=>'FM','value'=>'MICRONESIA, FEDERACIÓN DE ESTADOS DE (Yap, Kosrae, Truk, Pohnpei)']);
        CountryCode::create(['cod'=>'MD','value'=>'MOLDAVIA']);
        CountryCode::create(['cod'=>'MC','value'=>'MÓNACO']);
        CountryCode::create(['cod'=>'MN','value'=>'MONGOLIA']);
        CountryCode::create(['cod'=>'ME','value'=>'MONTENEGRO']);
        CountryCode::create(['cod'=>'MS','value'=>'MONTSERRAT']);
        CountryCode::create(['cod'=>'MZ','value'=>'MOZAMBIQUE']);
        CountryCode::create(['cod'=>'MM','value'=>'MYANMAR (Antigua Birmania)']);
        CountryCode::create(['cod'=>'NA','value'=>'NAMIBIA']);
        CountryCode::create(['cod'=>'NR','value'=>'NAURU']);
        CountryCode::create(['cod'=>'CX','value'=>'NAVIDAD, ISLA']);
        CountryCode::create(['cod'=>'NP','value'=>'NEPAL']);
        CountryCode::create(['cod'=>'NI','value'=>'NICARAGUA (incluidas las Islas del Maíz)']);
        CountryCode::create(['cod'=>'NE','value'=>'NÍGER']);
        CountryCode::create(['cod'=>'NG','value'=>'NIGERIA']);
        CountryCode::create(['cod'=>'NU','value'=>'NIUE, ISLA']);
        CountryCode::create(['cod'=>'NF','value'=>'NORFOLK, ISLA']);
        CountryCode::create(['cod'=>'NO','value'=>'NORUEGA, (Incluidos la Isla Jan Mayen y el archipiélago Svalbard)']);
        CountryCode::create(['cod'=>'NC','value'=>'NUEVA CALEDONIA (Incluidas las islas Lealtad: Maré, Lifou y Ouvéa)']);
        CountryCode::create(['cod'=>'NZ','value'=>'NUEVA ZELANDA']);
        CountryCode::create(['cod'=>'IO','value'=>'OCÉANO ÍNDICO, TERRITORIO BRITÁNICO DEL (Archipiélago de Chagos)']);
        CountryCode::create(['cod'=>'OM','value'=>'OMÁN']);
        CountryCode::create(['cod'=>'NL','value'=>'PAÍSES BAJOS (parte europea)']);
        CountryCode::create(['cod'=>'BQ','value'=>'PAÍSES BAJOS (parte caribeña: Bonaire, San Eustaquio y Saba; antes en Antillas Neerlandesas)']);
        CountryCode::create(['cod'=>'PK','value'=>'PAKISTÁN']);
        CountryCode::create(['cod'=>'PW','value'=>'PALAU']);
        CountryCode::create(['cod'=>'PA','value'=>'PANAMÁ (incluida la antigua Zona del Canal)']);
        CountryCode::create(['cod'=>'PG','value'=>'PAPÚA NUEVA GUINEA (Parte oriental de Nueva Guinea; Archipiélago Bismarck (incluidas: Nueva Bretaña, Nueva Irlanda, Lavongai y las Islas del Almirantazgo); Islas Salomón del Norte (Bougainville y Buka); Islas Trobriand, Islas Woodlark, Islas Entrecasteaux y Archipiélago de la Lousiade)']);
        CountryCode::create(['cod'=>'PY','value'=>'PARAGUAY']);
        CountryCode::create(['cod'=>'PE','value'=>'PERÚ']);
        CountryCode::create(['cod'=>'PN','value'=>'PITCAIRN (incluidas las Islas Henderson, Ducie y Oeno)']);
        CountryCode::create(['cod'=>'PF','value'=>'POLINESIA FRANCESA (Islas Marquesas, Isla de la Sociedad (incluido Tahiti), Islas Gambier, Islas Tuamotú e islas Australes incluida la Isla de Clipperton)']);
        CountryCode::create(['cod'=>'PL','value'=>'POLONIA']);
        CountryCode::create(['cod'=>'PT','value'=>'PORTUGAL (Incluidos los Archipiélagos de las Azores y de Madeira)']);
        CountryCode::create(['cod'=>'PR','value'=>'PUERTO RICO']);
        CountryCode::create(['cod'=>'QA','value'=>'QATAR']);
        CountryCode::create(['cod'=>'GB','value'=>'REINO UNIDO (Gran Betraña e Irlanda del Norte)']);
        CountryCode::create(['cod'=>'RW','value'=>'RUANDA']);
        CountryCode::create(['cod'=>'RO','value'=>'RUMANÍA']);
        CountryCode::create(['cod'=>'RU','value'=>'RUSIA (FENERACIÓN DE)']);
        CountryCode::create(['cod'=>'SB','value'=>'SALAMÓN, ISLAS']);
        CountryCode::create(['cod'=>'SV','value'=>'SALVADOR, EL']);
        CountryCode::create(['cod'=>'WS','value'=>'SAMOA (Samoa Occidental)']);
        CountryCode::create(['cod'=>'AS','value'=>'SAMOA AMERICANA']);
        CountryCode::create(['cod'=>'KN','value'=>'SAN CRISTÓBAL Y NIEVES (Saint Kitts y Nevis)']);
        CountryCode::create(['cod'=>'SM','value'=>'SAN MARINO']);
        CountryCode::create(['cod'=>'SX','value'=>'SAN MARTÍN (parte meridional; antes en Antillas Neerlandesas)']);
        CountryCode::create(['cod'=>'PM','value'=>'SAN PEDRO Y MIQUELÓN']);
        CountryCode::create(['cod'=>'VC','value'=>'SAN VICENTE Y LAS GRANADINAS']);
        CountryCode::create(['cod'=>'SH','value'=>'SANTA ELENA (Incluidos la Isla de la Ascensión y el Archipiélago Tristán da Cuhna)']);
        CountryCode::create(['cod'=>'LC','value'=>'SANTA LUCÍA']);
        CountryCode::create(['cod'=>'ST','value'=>'SANTO TOMÉ Y PRINCIPE']);
        CountryCode::create(['cod'=>'SN','value'=>'SENEGAL']);
        CountryCode::create(['cod'=>'RS','value'=>'SERBIA']);
        CountryCode::create(['cod'=>'SC','value'=>'SEYCHELLES (Islas Mahé, Isla Praslin, La Digue, Fragata y Silhouette, Islas Almirantes (entre ellas Desroches, Alphonse, Plate y Coëtivy); Islas Farquhar (entre ellas Providencia); Islas Aldabra e Islas Cosmoledo.)']);
        CountryCode::create(['cod'=>'SL','value'=>'SIERRA LEONA']);
        CountryCode::create(['cod'=>'SG','value'=>'SINGAPUR']);
        CountryCode::create(['cod'=>'SY','value'=>'SIRIA (REPÚBLICA ÁRABE)']);
        CountryCode::create(['cod'=>'SO','value'=>'SOMALIA']);
        CountryCode::create(['cod'=>'LK','value'=>'SRI LANKA']);
        CountryCode::create(['cod'=>'SZ','value'=>'SUAZILANDA']);
        CountryCode::create(['cod'=>'ZA','value'=>'SUDÁFRICA']);
        CountryCode::create(['cod'=>'SD','value'=>'SUDÁN']);
        CountryCode::create(['cod'=>'SS','value'=>'SUDÁN DEL SUR']);
        CountryCode::create(['cod'=>'SE','value'=>'SUECIA']);
        CountryCode::create(['cod'=>'CH','value'=>'SUIZA (Incluidos el territorio alemán de Büsingen y el municipio italiano de Campione de Italia)']);
        CountryCode::create(['cod'=>'SR','value'=>'SURINAM']);
        CountryCode::create(['cod'=>'TH','value'=>'TAILANDA']);
        CountryCode::create(['cod'=>'TW','value'=>'TAIWÁN']);
        CountryCode::create(['cod'=>'TZ','value'=>'TANZANIA (REPÚBLICA UNIDA DE) (Tanganica e islas de Zanzibar y Pemba)']);
        CountryCode::create(['cod'=>'TJ','value'=>'TAYIKISTÁN']);
        CountryCode::create(['cod'=>'PS','value'=>'TERRITORIO PALESTINO OCUPADO (Cisjordania y Franja de Gaza)']);
        CountryCode::create(['cod'=>'TF','value'=>'TIERRAS AUSTRALES FRANCESAS (Isla de Nueva Amsterdam, Isla San Pablo, las Islas Crozet y Kerguelén)']);
        CountryCode::create(['cod'=>'TL','value'=>'TIMOR LESTE']);
        CountryCode::create(['cod'=>'TG','value'=>'TOGO']);
        CountryCode::create(['cod'=>'TK','value'=>'TOKELAU, ISLAS']);
        CountryCode::create(['cod'=>'TO','value'=>'TONGA']);
        CountryCode::create(['cod'=>'TT','value'=>'TRINIDAD Y TOBAGO']);
        CountryCode::create(['cod'=>'TN','value'=>'TÚNEZ']);
        CountryCode::create(['cod'=>'TC','value'=>'TURCAS Y CAICOS, ISLAS']);
        CountryCode::create(['cod'=>'TM','value'=>'TURKMENISTATÁN']);
        CountryCode::create(['cod'=>'TR','value'=>'TURQUÍA']);
        CountryCode::create(['cod'=>'TV','value'=>'TUVALU']);
        CountryCode::create(['cod'=>'UA','value'=>'UCRANIA']);
        CountryCode::create(['cod'=>'UG','value'=>'UGANDA']);
        CountryCode::create(['cod'=>'UY','value'=>'URUGUAY']);
        CountryCode::create(['cod'=>'UZ','value'=>'UZBEKISTÁN']);
        CountryCode::create(['cod'=>'VU','value'=>'VANUATU']);
        CountryCode::create(['cod'=>'VA','value'=>'VATICANO, CIUDAD DEL (Santa Sede)']);
        CountryCode::create(['cod'=>'VE','value'=>'VENEZUELA']);
        CountryCode::create(['cod'=>'VN','value'=>'VIETNAM']);
        CountryCode::create(['cod'=>'VG','value'=>'VÍRGENES BRITÁNICAS, ISLAS']);
        CountryCode::create(['cod'=>'VI','value'=>'VÍRGENES DE LOS EE.UU, ISLAS']);
        CountryCode::create(['cod'=>'WF','value'=>'WALLIS Y FUTUNA, ISLAS (incluida la Isla Alofi )']);
        CountryCode::create(['cod'=>'YE','value'=>'YEMEN (Yemen del Norte y Yemen del Sur)']);
        CountryCode::create(['cod'=>'DJ','value'=>'YIBUTI']);
        CountryCode::create(['cod'=>'ZM','value'=>'ZAMBIA']);
        CountryCode::create(['cod'=>'ZW','value'=>'ZIMBABWE']);
        CountryCode::create(['cod'=>'QU','value'=>'OTROS PAÍSES O TERRITORIOS NO RELACIONADOS']);
        CountryCode::create(['cod'=>'XB','value'=>'BANCO CENTRAL EUROPEO']);
        CountryCode::create(['cod'=>'XU','value'=>'INSTITUCIONES DE LA UNIÓN EUROPEA']);
        CountryCode::create(['cod'=>'XN','value'=>'ORGANISMOS INTERNACIONALES DISTINTOS DE LAS INSTITUCIONES DE LA UNIÓN EUROPEA Y DEL BANCO CENTRAL EUROPEO']);
    }
}
